name: Deploy da AplicaÃ§Ã£o Laravel ğŸš€

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy para ProduÃ§Ã£o ğŸš€
    runs-on: ubuntu-latest

    steps:
      - name: Configurar PHP ğŸ˜
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"

      - name: Fazer Checkout do CÃ³digo ğŸ“¥
        uses: actions/checkout@v4

      - name: Copiar Arquivo .env ğŸ“„
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Definir VariÃ¡veis de Ambiente ğŸŒ¿
        run: |
          sed -i "s/^DB_DATABASE=.*/DB_DATABASE=${{ secrets.DB_DATABASE }}/" .env
          sed -i "s/^DB_HOST=.*/DB_HOST=${{ secrets.DB_HOST }}/" .env
          sed -i "s/^DB_USERNAME=.*/DB_USERNAME=${{ secrets.DB_USERNAME }}/" .env
          sed -i "s/^DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/" .env
          sed -i "s/^MAIL_HOST=.*/MAIL_HOST=${{ secrets.MAIL_HOST }}/" .env
          sed -i "s/^MAIL_PORT=.*/MAIL_PORT=${{ secrets.MAIL_PORT }}/" .env
          sed -i "s/^MAIL_USERNAME=.*/MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}/" .env
          sed -i "s/^MAIL_PASSWORD=.*/MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}/" .env
          sed -i "s/^MAIL_FROM_ADDRESS=.*/MAIL_FROM_ADDRESS=${{ secrets.MAIL_FROM_ADDRESS }}/" .env

      - name: Instalar DependÃªncias ğŸ“¦
        run: composer install --no-dev --no-scripts --prefer-dist

      - name: Instalar DependÃªncias NPM ğŸ“¦
        run: npm install

      - name: Compilar Assets NPM ğŸ› ï¸
        run: npm run build

      - name: Gerar Chave da AplicaÃ§Ã£o ğŸ”‘
        run: php artisan key:generate

      - name: Deploy para o FTP ğŸŒ
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

      - name: Upload de node_modules
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: node_modules/
          server-dir: public_html/node_modules/

