name: Deploy da AplicaÃ§Ã£o Laravel ğŸš€

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy para ProduÃ§Ã£o ğŸš€
    runs-on: ubuntu-latest

    steps:
      - name: Configurar PHP ğŸ˜
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.0"

      - name: Fazer Checkout do CÃ³digo ğŸ“¥
        uses: actions/checkout@v4

      - name: Definir VariÃ¡veis de Ambiente ğŸŒ¿
        run: |
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> .env
          echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "MAIL_FROM_ADDRESS=${{ secrets.MAIL_FROM_ADDRESS }}" >> .env
      - name: Instalar DependÃªncias ğŸ“¦
        run: composer install --no-dev --no-scripts --prefer-dist

      - name: Gerar Chave da AplicaÃ§Ã£o ğŸ”‘
        run: php artisan key:generate

      - name: Deploy para o FTP ğŸŒ
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
